version: '3.8'

services:
  db:
    image: postgres:13-alpine
    user: postgres
    environment:
      - POSTGRES_DB=history_db
      - POSTGRES_USER=history_user2
      - POSTGRES_PASSWORD=pass
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  test_py37:
    image: python:3.7-slim-bullseye
    command: sh -c "
      cd pycaption;
      pip install --upgrade pip;
      pip install -r test_requirements.txt;
      pip install -e .;
      python runtests.py -vv --html=./test-results_py37.html --self-contained-html --cov=pycaption --cov-report=term-missing:skip-covered;
      "
    volumes:
      - .:/pycaption
    depends_on:
      - db

  test_py38:
    image: python:3.8-slim-bullseye
    command: sh -c "
      cd pycaption;
      pip install --upgrade pip;
      pip install -r test_requirements.txt;
      pip install -e .;
      python runtests.py -vv --html=./test-results_py38.html --self-contained-html --cov=pycaption --cov-report=term-missing:skip-covered;
      "
    volumes:
      - .:/pycaption
    depends_on:
      - db

  test_py39:
    image: python:3.9-slim-bullseye
    command: sh -c "
      cd pycaption;
      pip install --upgrade pip;
      pip install -r test_requirements.txt;
      pip install -e .;
      python runtests.py -vv --html=./test-results_py39.html --self-contained-html --cov=pycaption --cov-report=term-missing:skip-covered;
      "
    volumes:
      - .:/pycaption
    depends_on:
      - db

volumes:
  pgdata:
    driver: local