name: Publish PyCaption to Test PyPI

on: workflow_dispatch

jobs:
  call-unit-tests-workflow:
    name: Run unit tests
    uses: ./.github/workflows/main.yml
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}

  build-n-publish:
    name: Build and publish PyCaption to Test PyPI
    needs: call-unit-tests-workflow
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        python -m pip install --upgrade twine

    - name: Build package
      run: python -m build
      timeout-minutes: 10

    - name: Publish package on Test PyPI
      run: python -m twine upload --verbose dist/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        TWINE_REPOSITORY:  "testpypi"
